In [1]:
%matplotlib notebook

In [2]:
import inspec_fits
run_name = 'objects_to_fit'
path_spiders_fits = 'data/spiders_quasar_bhmass-DR14.fits'

In [3]:
gui = inspec_fits.inspec(run_name, path_spiders_fits)

<IPython.core.display.Javascript object>

In [16]:
import numpy
choices_fits = numpy.load('choices_fits.npy')
inds_to_plot = numpy.where(choices_fits[:,0] == 1)[0]
numpy.save('inds_to_plot', inds_to_plot)

In [4]:
import numpy
inds = numpy.load('objects_to_fit.npy')
inds.shape, inds

((206,),
 array([   1,    4,    6,   13,   14,   17,   25,   26,   32,   36,   37,
          43,   46,   49,   50,   53,   54,   56,   61,   64,   65,   66,
          67,   69,   75,   77,   78,   80,   81,   86,   87,   88,   89,
          90,   92,   94,   96,   97,  101,  104,  105,  107,  108,  112,
         116,  121,  122,  123,  124,  125,  127,  129,  131,  133,  138,
         141,  146,  148,  154,  160,  166,  168,  173,  178,  187,  189,
         193,  197,  200,  204,  206,  208,  213,  216,  218,  220,  221,
         225,  229,  231,  233,  234,  236,  237,  241,  242,  252,  255,
         256,  264,  265,  266,  268,  269,  271,  278,  284,  287,  294,
         301,  302,  304,  308,  313,  315,  318,  325,  327,  328,  329,
         337,  338,  342,  344,  347,  349,  351,  356,  357,  360,  361,
         366,  368,  376,  387,  388,  389,  411,  416,  419,  429,  435,
         436,  439,  444,  445,  461,  491,  500,  504,  505,  506,  507,
         522,  535,  540,  55

In [15]:
choices_fits = numpy.load('choices_fits.npy')
choices_fits[inds]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [21]:
choices_fits = numpy.load('choices_fits.npy')
choices_fits[80]

array([0, 0, 0])

In [1]:
!rm choices_fits.npy

In [5]:
import numpy
inds = numpy.load('objects_to_fit.npy')
inds

array([  1,   4,   6,  13,  14,  17,  25,  26,  32,  36,  37,  43,  46,
        49,  50,  53,  54,  56,  61,  64,  65,  66,  67,  69,  75,  77,
        78,  80,  81,  86,  87,  88,  89,  90,  92,  94,  96,  97, 101,
       104, 105, 107, 108, 112, 116, 121, 122, 123, 124, 125, 127, 129,
       131, 133, 138, 141, 146, 148, 154, 160, 166, 168, 173, 178, 187,
       189, 193, 197, 200, 204, 206, 208, 213, 216, 218, 220, 221, 225,
       229, 231, 233, 234, 236, 237, 241, 242, 252, 255, 256, 264, 265,
       266, 268, 269, 271, 278, 284, 287, 294, 301, 302, 304, 308, 313,
       315, 318, 325, 327, 328, 329, 337, 338, 342, 344, 347, 349, 351,
       356, 357, 360, 361, 366, 368, 376, 387, 388, 389])

In [13]:
choices_fits = numpy.load('choices_fits.npy')
#choices = numpy.load('choices.npy')

In [10]:
choices_fits_tot = numpy.zeros((choices.shape[0],3), dtype=int)

In [11]:
choices_fits_tot[inds] = choices_fits

In [12]:
numpy.save('choices_fits.npy', choices_fits_tot)


In [17]:
choices_fits[inds,0].shape

(127,)